# based in part on:
# https://github.com/htpcBeginner/docker-traefik/docker-compose-t2.yml

networks:
  proxy_network:
    name: proxy_network
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.60.0.0/24
          # 128 dhcp hosts allowed, 128 static addresses
          ip_range: 10.60.0.128/25
          gateway: 10.60.0.1
          aux_addresses:
            web: 10.60.0.4
            traefik: 10.60.0.5
            portainer: 10.60.0.5
            portainer-agent-virt1: 10.60.0.6
            portainer-agent-virt2: 10.60.0.7
            jenkins: 10.60.0.10
            netboot: 10.60.0.11
            pihole: 10.60.0.14
            speedtest: 10.60.0.13
            starbase-80: 10.60.0.12
            uptime-kuma: 10.60.0.14
            vault/docker: 10.60.0.24

services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:v2.10.4
    restart: unless-stopped

    environment:
      - BASIC_AUTH_PASSWORD_HASH=${BASIC_AUTH_PASSWORD_HASH}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - CLOUDFLARE_DNS_API_TOKEN="${CLOUDFLARE_DNS_API_TOKEN}"
      - CLOUDFLARE_EMAIL="${CLOUDFLARE_EMAIL}"
      - TZ=${TZ}

    extra_hosts:
      - storage.docker.internal:10.50.0.70

    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 15s
      retries: 3

    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.cattivi.com`) # Define the subdomain for the traefik dashboard.
      - traefik.http.routers.api.service=api@internal # Enable Traefik API.
      # protect dashboard with basic auth and restrict access to private class subnets only:
      - traefik.http.routers.api.middlewares=local-ipwhitelist@file,basic-auth@file
      - traefik.http.middlewares.basic-auth-global.basicauth.users=${BASIC_AUTH_USER}:${BASIC_AUTH_PASSWORD_HASH}

    networks:
      proxy_network:
        ipv4_address: 10.60.0.5

    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 8080:8080 # MGMT WEB UI

    security_opt:
      - no-new-privileges:true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./data:/etc/traefik
      - /mnt/cache/appdata/traefik/data:/etc/traefik
      # - ./logs:/logs
      - /mnt/cache/appdata/traefik/logs:/logs
      - ./certs/acme-production.json:/etc/traefik/certs/acme-production.json
      - ./certs/acme-staging.json:/etc/traefik/certs/acme-staging.json
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./file-watcher.yaml:/etc/traefik/file-watcher.yaml
