version: '3.8'

name: immich

services:
  immich-tailscale:
    container_name: immich-tailscale
    hostname: photos
    image: tailscale/tailscale:latest
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS="${TS_EXTRA_ARGS}"
      - TS_SERVE_CONFIG=${TS_SERVE_CONFIG}
      - TS_STATE_DIR=${TS_STATE_DIR}
      - TS_USERSPACE=${TS_USERSPACE}
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    restart: unless-stopped

    depends_on:
      - redis
      - database
      - immich-tailscale

    environment:
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      IMMICH_VERSION: ${IMMICH_VERSION}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      UPLOAD_LOCATION: ${UPLOAD_LOCATION}

    networks:
      - proxy_network

    ports:
      - 2283:3001

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    restart: unless-stopped
 
    depends_on:
      - redis
      - database
 
    environment:
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      IMMICH_VERSION: ${IMMICH_VERSION}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      UPLOAD_LOCATION: ${UPLOAD_LOCATION}

    networks:
      - proxy_network
 
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro 

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    restart: unless-stopped

    environment:
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      IMMICH_VERSION: ${IMMICH_VERSION}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      UPLOAD_LOCATION: ${UPLOAD_LOCATION}

    networks:
      - proxy_network

    volumes:
      - immich_model_cache:/cache

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped

    environment:
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      IMMICH_VERSION: ${IMMICH_VERSION}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      UPLOAD_LOCATION: ${UPLOAD_LOCATION}

    networks:
      - proxy_network

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: unless-stopped

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}

    networks:
      - proxy_network

    volumes:
      - immich_pg_data:/var/lib/postgresql/data

#####################################################################
networks:
 proxy_network:
   external: true

volumes:
  immich_pg_data:
  immich_model_cache:
