---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true

- search:
    provider: google
    target: _blank

- openmeteo:
    label: San Jose # optional
    latitude: 37.335480
    longitude: -121.893028
    timezone: America/Los_Angeles # optional
    units: imperial # metric or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

# - unifi_console:
#     url: https://unifi.host.or.ip:port
#     username: user
#     password: pass
#     site: cattivi.com # optional
