#####################################################################
# Based largely on https://github.com/netbootxyz/docker-netbootxyz/blob/master/docker-compose.yml.example

services:
  netboot:
    container_name: netboot
    image: ghcr.io/netbootxyz/netbootxyz
    restart: unless-stopped

    # commenting out so we use latest always
    # environment:
      # - MENU_VERSION=2.0.47 # optional

    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.netboot.rule=Host(`netboot.cattivi.com`)"
      - "traefik.http.routers.netboot.entrypoints=websecure"
      - "traefik.http.routers.netboot.service=web"
      # - "traefik.http.routers.web.tls.certresolver=default"
      - "traefik.http.services.netboot.loadbalancer.server.port=443"
      - "net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/netboot.png"

    networks:
      proxy_network:
        ipv4_address: 10.60.0.11

    ports:
      - 1080:3000       # web admin port
      - 69:69/udp
      # - 1080:80       # optional nginx for asset serving

    volumes:
      - /mnt/cache/appdata/netboot/netboot_config:/config # optional
      - /mnt/cache/appdata/netboot/netboot_assets:/assets # optional
      # - ./netboot_config:/config # optional
      # - ./netboot_assets:/assets # optional

networks:
 proxy_network:
   external: true
