version: '3'

services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - API_KEY=${CF_API_TOKEN}
      - ZONE=cattivi.com
      # - SUBDOMAIN=subdomain
      - PROXIED=true
