services:
  reverse-proxy:
    container_name: reverse-proxy
    # image: caddy:latest
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "2019:2019" # admin port
      - "80:80"     # we should just stop publishing 80 and 443, rely on reverse-proxy
      - "443:443"
      - "443:443/udp"
    environment:
      DOMAIN: "https://cattivi.com"  
      EMAIL: "ashebanow@cattivi.com"                 
      LOG_FILE: "/data/access.log"
    volumes:
      - ./Caddyfile-web:/etc/caddy/Caddyfile:ro
      - ./site:/srv
      - /mnt/user/appdata/reverse-proxy/data:/data
      - /mnt/user/appdata/reverse-proxy/config:/config
      - /mnt/user/appdata/reverse-proxy/test_code:/wdata
      # - ./data:/data
      # - ./config:/config
      # - ./test_code:/wdata
