version: '3.9'

configs:
  caddy_config:
    file: ./Caddyfile

services:
  caddy:
    container_name: web
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CATTIVI_SITE_ADDRESS=10.40.0.124:8001
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    volumes:
      - ./site:/srv
      - /mnt/user/appdata/caddy/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
