version: '3.9'

configs:
  caddy_config:
    file: ./Caddyfile

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8001:80"
      - "4431:443"
      - "4431:443/udp"
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    volumes:
      - ./site:/srv
      - /mnt/user/appdata/caddy/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
