services:
  caddy:
    container_name: web
    # image: caddy:latest
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "2019:2019" # admin port
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      DOMAIN: "https://cattivi.com"  
      EMAIL: "ashebanow@cattivi.com"                 
      LOG_FILE: "/data/access.log"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv
      - /mnt/user/appdata/caddy/data:/data
      - /mnt/user/appdata/caddy/config:/config
      - /mnt/user/appdata/caddy/test_code:/wdata
      # - ./data:/data
      # - ./config:/config
      # - ./test_code:/wdata
