version: '3.9'

services:
  caddy:
    container_name: web
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8001:80"
      - "4431:443"
      - "4431:443/udp"
    environment:
      - CATTIVI_SITE_ADDRESS=10.40.0.124
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - /mnt/user/appdata/caddy/data:/data
      - /mnt/user/appdata/caddy/config:/config
