version: '2'
services:
  mysql:
    image: mysql:8.2

    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

    networks:
      - proxy_network

    volumes:
      - mysql-data:/var/lib/mysql

  #####################################################################
  bookstack:
    image: solidnerd/bookstack:24.2.0
  
    depends_on:
      - mysql

    environment:
      - DB_HOST=mysql:3306
      - DB_DATABASE=$MYSQL_DATABASE
      - DB_USERNAME=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
      #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
      - APP_URL=$APP_URL
      # APP_KEY is used for encryption where needed, so needs to be persisted to
      # preserve decryption abilities.
      # Can run `php artisan key:generate` to generate a key
      - APP_KEY=$APP_KEY

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.rule=Host(`documentation.cattivi.com`)"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - "traefik.http.routers.bookstack.service=bookstack"
      # - "traefik.http.routers.bookstack.tls.certresolver=default"
      - "traefik.http.services.bookstack.loadbalancer.server.port=8765"

    networks:
      - proxy_network

    volumes:
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/storage/uploads

    ports:
      - "8080:8080"

#####################################################################
networks:
 proxy_network:
   external: true

#####################################################################
volumes:
 mysql-data:
 uploads:
 storage-uploads:
