version: '3.3'

services:
  uptime:
    container_name: uptime
    hostname: uptime
    image: louislam/uptime-kuma:latest
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.cattivi.com`)"
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.service=uptime"
      # - "traefik.http.routers.uptime.tls.certresolver=default"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"

    networks:
      proxy_network:
        ipv4_address: 10.60.0.14

    ports:
      - 3001:3001  # <Host Port>:<Container Port>

    volumes:
      # - ./data:/app/data
      - /mnt/cache/appdata/uptime/data:/app/data
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
 proxy_network:
   external: true