services:
  blog:
    build: .
    container_name: blog
    hostname: blog
    restart: unless-stopped

    depends_on:
      - blog-mysql

    environment:
      url: http://10.60.0.7:3080

      database__client: mysql
      database__connection__host: blog-mysql
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}

      # contrary to the default mentioned in the linked documentation, this
      # image defaults to NODE_ENV=production (so development mode needs to
      # be explicitly specified if desired)
      NODE_ENV: development

      # Useful debugging settings for development mode:
      # DEBUG: ghost:*,ghost-config
      DEBUG: ghost-storage-cloudinary:*
      # DEBUG: ghost:*,ghost-config,ghost-storage-cloudinary:*

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.cattivi.com`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.service=blog"
      - "traefik.http.routers.blog.tls.blog=letsencrypt"
      - "traefik.http.services.blog.loadbalancer.server.port=3080"

    networks:
      proxy_network:
        ipv4_address: 10.60.0.7

    ports:
      - 3080:2368

    volumes:
      - ./config.development.json:/var/lib/ghost/config.development.json
      - ./config.production.json:/var/lib/ghost/config.production.json
      # - ./content:/var/lib/ghost/content
      - /mnt/cache/appdata/blog/content:/var/lib/ghost/content

  blog-mysql:
    container_name: blog-mysql
    hostname: blog-mysql
    image: mariadb:latest
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    networks:
      proxy_network:
        ipv4_address: 10.60.0.21

    volumes:
      # - ./mysql-data:/var/lib/mysql
      - /mnt/cache/appdata/blog/mysql:/var/lib/mysql

networks:
 proxy_network:
   external: true