version: '3.3'

labels:
    - "traefik.enable=true"
    - "traefik.http.routers.speedtest.rule=Host('speedtest.cattivi.com')"
    - "traefik.http.routers.speedtest.entrypoints=websecure"
    - "traefik.http.routers.speedtest.service=speedtest"
  # - "traefik.http.routers.portainer.tls.certresolver=staging"
    - "traefik.http.services.speedtest.loadbalancer.server.port=8765"

services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker:latest
        ports:
            - 8765:80
        volumes:
            - /mnt/user/appdata/speedtest/config:/config
        environment:
            - TZ=America/Los_Angeles
            # - PGID=
            # - PUID=
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
