version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10.4
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - 8000:80
      - 4430:443
      - 8081:8080  # (optional) expose the dashboard !don't use in production!
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

