version: '3.9'

services:
  reverse-proxy:
    image: traefik:v2.10.4
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
      # - 8081:8080  # (optional) expose the dashboard !don't use in production!
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      # - ./data:/data
      - /mnt/appdata/traefik:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
