version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10.4
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # (optional) expose the dashboard !don't use in production!
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - etc-traefik:/etc/traefik
      - /mnt/user/appdata/traefik:/data
    restart: unless-stopped
