# based in part on:
# https://github.com/htpcBeginner/docker-traefik/docker-compose-t2.yml

networks:
  proxy_network:
    name: proxy_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.60.0.0/24
          gateway: 10.60.0.1

services:
  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    image: traefik:v2.10.4
    restart: unless-stopped

    environment:
      - BASIC_AUTH_PASSWORD_HASH=${BASIC_AUTH_PASSWORD_HASH}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - CLOUDFLARE_DNS_API_TOKEN="${CLOUDFLARE_DNS_API_TOKEN}"
      - CLOUDFLARE_EMAIL="${CLOUDFLARE_EMAIL}"
      - TZ=${TZ}

    extra_hosts:
      - storage.docker.internal:10.50.0.70

    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 15s
      retries: 3

    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`reverse-proxy.cattivi.com`) # Define the subdomain for the traefik dashboard.
      - traefik.http.routers.api.service=api@internal # Enable Traefik API.
      # protect dashboard with basic auth and restrict access to private class subnets only:
      - traefik.http.routers.api.middlewares=local-ipwhitelist@file,basic-auth@file
      - traefik.http.middlewares.basic-auth-global.basicauth.users=${BASIC_AUTH_USER}:${BASIC_AUTH_PASSWORD_HASH}

    networks:
      proxy_network:
        ipv4_address: 10.60.0.4

    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 127.0.0.1:8080:8080 # MGMT WEB UI

    security_opt:
      - no-new-privileges:true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./data:/etc/traefik
      - /mnt/cache/appdata/traefik/data:/etc/traefik
      # - ./logs:/logs
      - /mnt/cache/appdata/traefik/logs:/logs
      - ./certs/acme-production.json:/etc/traefik/certs/acme-production.json
      - ./certs/acme-staging.json:/etc/traefik/certs/acme-staging.json
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./file-watcher.yaml:/etc/traefik/file-watcher.yaml
