global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# Log information
# ---
log:
  level: WARNING  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /data/log/traefik.log

# Accesslog
# ---
accesslog:
  format: common  # common, json, logfmt
  filePath: /data/log/access.log

# Disable API and Dashboard
# ---
api:
 dashboard: true  # true by default
 insecure: true  # Don't do this in production!

# Ping configuration
ping: {}

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    # Redirect to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  staging:
    acme:
      email: ashebanow@cattivi.com
      storage: /etc/traefik/certs/acme-staging.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
  production:
    acme:
      email: ashebanow@cattivi.com
      storage: /etc/traefik/certs/acme-production.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

# (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem

# (Optional) Disable TLS version 1.0 and 1.1
options:
  default:
    minVersion: VersionTLS12

providers:
  docker:
    exposedByDefault: false  # Default is true
    endpoint: "unix:///var/run/docker.sock"
    # Unfortunately traefik doesn't allow multiple docker endpoints.
    # Need to use swarm.
    #
    # endpoint: "ssh://ashebanow@storage.local:9001"
    # endpoint: "ssh://ashebanow@virt1.local:9001"
    # endpoint: "ssh://ashebanow@virt2.local:9001"
    #
    # liquid-ubuntu WSL2:
    # endpoint: "ssh://traefik@172.26.103.196:9001"
    
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true
