global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# Log information
# ---
log:
  level: WARNING  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /data/log/traefik.log

# Accesslog
# ---
accesslog:
  format: common  # common, json, logfmt
  filePath: /data/log/access.log

# Disable API and Dashboard
# ---
api:
 dashboard: false  # true by default
 insecure: false  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    # (Optional) Redirect to HTTPS
    # ---
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  websecure:
    address: :443

# Configure your CertificateResolver here...
# ---
# certificatesResolvers:
#   staging:
#     acme:
#       email: ashebanow@gmail.com
#       storage: /data/letsencrypt/acme.json
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       httpChallenge:
#         entryPoint: web
#   production:
#     acme:
#       email: ashebanow@gmail.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       httpChallenge:
#         entryPoint: web

# (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem

# (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

providers:
  docker:
    exposedByDefault: false  # Default is true
    endpoint: "unix:///var/run/docker.sock"
    # Unfortunately traefik doesn't allow multiple docker endpoints.
    # Need to use swarm.
    #
    # endpoint: "ssh://ashebanow@storage:9001"
    # endpoint: "ssh://ashebanow@virt1:9001"
    # virt2 VM:
    # endpoint: "ssh://ashebanow@virt2:9001"
    # liquid-ubuntu WSL2:
    # endpoint: "ssh://traefik@172.26.103.196:9001"
    
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true
