version: '3'

#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    hostname: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped

    environment:
      - TZ=America/Los_Angeles

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`homarr.cattivi.com`)"
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.routers.homarr.service=homarr"
      # - "traefik.http.routers.homarr.tls.certresolver=default"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"

    networks:
      proxy_network:
        ipv4_address: 10.60.0.19

    ports:
      - '7575:7575'

    volumes:
      # For debugging locally:
      # - ./data/configs:/app/data/configs
      # - ./data/icons:/app/public/icons
      - /mnt/cache/appdata/homarr/configs:/app/data/configs
      - /mnt/cache/appdata/homarr/icons:/app/public/icons

      - ./default.json:/app/data/configs/default.json
      - ./icons/infisical.svg:/app/public/icons/infisical.svg
      - /var/run/docker.sock:/var/run/docker.sock

networks:
 proxy_network:
   external: true