version: "3.9"

services:
  infisical:
    container_name: infisical
    image: nginx
    restart: always
    ports:
      - 7080:80
      - 7443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - infisical-frontend
      - infisical-backend
    networks:
      - infisical

  infisical-backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      - infisical-mongo
    image: infisical/backend
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - infisical

  infisical-frontend:
    container_name: infisical-frontend
    restart: unless-stopped
    depends_on:
      - infisical-backend
    image: infisical/frontend
    env_file: .env
    environment:
      # - NEXT_PUBLIC_POSTHOG_API_KEY=${POSTHOG_PROJECT_API_KEY}
      - INFISICAL_TELEMETRY_ENABLED=${TELEMETRY_ENABLED}
    networks:
      - infisical

  secret-scanning-git-app:
    container_name: infisical-secret-scanning-git-app
    restart: unless-stopped
    depends_on:
      - infisical-backend
      - infisical-frontend
      - infisical-mongo
    ports:
      - "7001:3001"
    image: infisical/staging_deployment_secret-scanning-git-app
    env_file: .env
    networks:
      - infisical

  infisical-mongo:
    container_name: infisical-mongo
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - /mnt/user/appdata/infisical-mongo/db:/data/db
    networks:
      - infisical

volumes:
  infisical-mongo-data:
    driver: local

networks:
  infisical:
