version: '3.9'

configs:
  glances_config:
    file: ./glances.conf

services:
  glances:
    container_name: glances
    hostname: glances
    image: nicolargo/glances:latest-full
    network_mode: "host"
    pid: "host"
    privileged: true
    restart: unless-stopped

    configs:
      - source: glances_config
      - target: /glances/config/glances.conf

    environment:
      GLANCES_OPT: "-C /glances/config/glances.conf -w"
      TZ: "Pacific/Los_Angeles"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.cattivi.com`)"
      - "traefik.http.routers.glances.entrypoints=websecure"
      - "traefik.http.routers.glances.service=glances"
      - "traefik.http.routers.glances.tls.certresolver=default"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
