services:
  glances:
    container_name: glances
    hostname: glances
    image: nicolargo/glances:latest-full
    network_mode: "host"
    pid: "host"
    privileged: true
    restart: unless-stopped

    environment:
      - GLANCES_OPT: "-C /etc/glances/glances.conf --webserver"
      - TZ: "Pacific/Los_Angeles"

    volumes:
      - "./glances.conf:/etc/glances/glances.conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
