version: '3.7'

services:
  ci:
    container_name: ci
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 4080:8080
      - 50000:50000
    volumes:
      - /mnt/user/appdata/ci/home:/var/jenkins_home
      # - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.port=4080"
      - "traefik.frontend.rule=Host:('ci.cattivi.com')"
