# Based largely on https://github.com/jonas-merkle/container-cloudflare-tunnel
version: '3.7'

# service description
services:
  # cloudflare tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    network_mode: "host"
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/cloudflare-tunnel/data:/home/nonroot/.cloudflared/
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
