version: '3'

services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:2.18.4
    ports:
      - 9001:9001 # for portainer->portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # note that this will work on a standard linux, but not
      # on my WSL ubuntu for some reason.``````
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped

networks:
 proxy_network:
   external: true