version: '3'

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ee:latest
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.cattivi.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"

    networks:
      proxy_network:
        ipv4_address: 10.60.0.13

    ports:
      # - 8000:8000 # for ssh to edge agents, optional
      - 9443:9443 # for admin UI

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./data:/data    # for testing purposes on unbuntu dev box
      - /mnt/cache/appdata/portainer:/data

networks:
 proxy_network:
   external: true