#####################################################################
networks:
  proxy_network:
    name: proxy_network
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.60.0.0/24
          # 128 dhcp hosts allowed, 128 static addresses
          ip_range: 10.60.0.128/25
          gateway: 10.60.0.1
          aux_addresses:
            auth: 10.60.0.3
            reverse-proxy: 10.60.0.4
            portainer: 10.60.0.5
            portainer-agent-virt1: 10.60.0.6
            portainer-agent-virt2: 10.60.0.7
            unifi: 10.60.0.8
            unifi-mongo: 10.60.0.9
            rancher: 10.60.0.10
            netboot: 10.60.0.11

# NOTE: This is not actually used in production, since we installed
# Portainer using UNRAID. We did change their config to match as much
# as possible.
services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ee:latest
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.cattivi.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.service=portainer"
      # - "traefik.http.routers.portainer.tls.certresolver=default"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"

    networks:
      proxy_network:
        ipv4_address: 10.60.0.5

    ports:
      # - 8000:8000 # for ssh to edge agents, optional
      - 9443:9443 # for admin UI

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./data:/data    # for testing purposes on unbuntu dev box
      - /mnt/cache/appdata/portainer:/data
