---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/ashebanow

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
    - Facebook:
        - abbr: FB
          href: https://facebook.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
